name: Push to GitLab

on:
  push:
    branches:
      - master  

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/nikhildhakad55/testingnikhil.git

      - name: Push to GitLab
        run: |
          git clone https://github.com/nikhildhakad55/docker_nodejs_demo.git  
          cd docker_nodejs_demo
          git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/nikhildhakad55/testingnikhil.git
          git checkout master 
          git push -uf gitlab main
