- name: Checkout GitHub repository
  uses: actions/checkout@v2

- name: Set up Git
  run: |
    git config --global user.name "GitHub Actions"
    git config --global user.email "actions@github.com"

- name: Add GitLab remote
  run: |
    git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/nikhildhakad55/demo.git

- name: Push to GitLab
  run: |
    git clone --depth 1 https://github.com/nikhildhakad55/docker_nodejs_demo.git # Fresh clone
    cd docker_nodejs_demo
    git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/nikhildhakad55/demo.git
    git push -uf gitlab main  # Push 'main' to GitLab
