name: Push to GitLab

on:
  push:
    branches:
      - master  # Trigger the workflow on the 'master' branch

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2

    - name: Rename the local branch to 'main'
      run: |
        git branch -M main  # Rename the branch to 'main'

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add GitLab remote
      run: |
        git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/nikhildhakad55/demo.git

    - name: Push to GitHub (origin)
      run: |
        git push -uf origin main  # Push 'main' to GitHub

    - name: Push to GitLab
      run: |
        git push -uf gitlab main  # Push 'main' to GitLab
