name: Push to GitLab

on:
  push:
    branches:
      - master  # Trigger the workflow on the 'master' branch

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add GitLab remote
      run: |
        git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/nikhildhakad55/demo.git

    - name: Fetch latest changes from GitLab (main branch)
      run: |
        git fetch gitlab main  # Fetch the latest changes from the GitLab 'main' branch

    - name: Attempt to merge GitLab main branch into GitHub master
      run: |
        git merge gitlab/main --allow-unrelated-histories || exit 0  # If merge fails, exit with status 0

    - name: Push code to GitLab
      run: |
        git push gitlab master:main  # Push 'master' branch from GitHub to 'main' branch in GitLab
