name: Push to GitLab

on:
  push:
    branches:
      - master  # Trigger the workflow on the 'master' branch

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add GitLab remote
      run: |
        git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/nikhildhakad55/demo.git

    - name: Fetch latest changes from GitLab (main branch)
      run: |
        git fetch gitlab main  # Fetch the latest changes from the GitLab 'main' branch

    - name: Rebase GitHub master branch onto GitLab main branch (resolve non-fast-forward)
      run: |
        git rebase gitlab/main  # Rebase the 'master' branch on top of the 'main' branch from GitLab

    - name: Push code to GitLab
      run: |
        git push gitlab master:main --force  # Force push 'master' branch from GitHub to 'main' branch in GitLab
